name: hello-world

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build steps
        run: echo "hello, demo build!"
    
  test:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: test steps
        run: echo "test demo!"
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy steps
        run: echo "deploy demo!"

    